#!/bin/sh
set -eu

uh7000ctl --json status >/tmp/uh7000-status.json
uh7000ctl --json playback-plan >/tmp/uh7000-playback-plan.json
grep -q 'io.github.carlodevil.UH7000.State.v1' /tmp/uh7000-status.json
grep -q '"channel": 4' /tmp/uh7000-playback-plan.json
test -f /usr/share/applications/io.github.carlodevil.UH7000.desktop
test -f /usr/share/dbus-1/services/io.github.carlodevil.UH7000.Control1.service
test -f /usr/share/alsa/ucm2/UH7000/HiFi.conf
